# Configuración Railway para múltiples servicios
# Uso: railway up --config railway.template.toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Servicio principal RAG
[[services]]
name = "rag-server"
build.command = "docker build -f Dockerfile.railway -t rag-server ."

[services.variables]
ENVIRONMENT = "railway"
PYTHONUNBUFFERED = "1"
VECTOR_DB_TYPE = "chroma"
SERVICE_TYPE = "rag_server"

[[services.domains]]
generate = true

# Servicio Redis (opcional)
[[services]]
name = "redis"
image = "redis:7-alpine"

[services.variables]
REDIS_SAVE = "60 1000"
REDIS_MAXMEMORY = "128mb"

# Variables compartidas entre servicios
[shared.variables]
OPENAI_MODEL = "gpt-3.5-turbo"
LOG_LEVEL = "INFO" 